<?php
/**
 * Created by PhpStorm.
 * User: Kundan
 * Date: 12/14/2018
 * Time: 12:32 PM
 */

namespace App\Providers;


use App\Blood;
use App\Category;
use App\Demand;
use App\events;
use App\Gallery;
use App\Post;
use App\Request;
use App\User;
use App\userdetail;
use Carbon\Laravel\ServiceProvider;
use App\Banner;

class CustomServiceProvider extends ServiceProvider
{
        public function __construct($app)
        {
            parent::__construct($app);
        }

        public function boot()
        {
            parent::boot(); // TODO: Change the autogenerated stub

            View()->composer('layouts.admin.*', function($data){
                $id = auth()->user()->id;
                if (\Gate::allows('isAdmin')) {
                    $users = User::count();
                    $demands = Demand::count();
                    $requests = Request::count();
                    $donates = Request::count();
                    $gallery = Gallery::count();
                    $events = events::count();
                    $posts = Post::count();
                    $category = Category::count();
                    $bloodgroup = Blood::where('id','=',auth()->user()->blood)->first();
                     $banner = Banner::latest()->first();
                    $bloodname = $bloodgroup->name;
                    $userdetail = userdetail::where('user_id','=',$id)->first();
                    if(!empty($userdetail )){
                        $point = $userdetail->count;
                    }else{
                        $point = 0;
                    }


                    $data->with(compact('users','demands','requests','donates','gallery','events','posts','category','bloodname','point'));


                }elseif(\Gate::allows('isUser') || \Gate::allows('isAuthor')){
                    $users = User::where('status','=',1)->count();
                    $demands = Demand::where('added_by','=',$id)->count();
                    $requests = Request::where('requested_by','=',$id)->count();
                    $donates = Request::where('requested_to','=',$id)->count();
                    $bloodgroup = Blood::where('id','=',auth()->user()->blood)->first();
                    $bloodname = $bloodgroup->name;
                    $userdetail = userdetail::where('user_id','=',$id)->first();
                    if(!empty($userdetail )){
                        $point = $userdetail->count;
                    }else{
                        $point = 0;
                    }
                     $banner = Banner::latest()->first();
                    $data->with(compact('users','demands','requests','donates','bloodname','point'));
                }

            });
            View()->composer('*', function($data){
                $banner = Banner::latest()->first();
                $data->with(compact('banner'));
            });
        }
}